name: Master

# TODO: only master, currently for testing
on: push
#  push:
#    branches: master

env:
  CACHE_IMAGE: docker.pkg.github.com/renovatebot/renovate/cache

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: ['slim'] #'latest',

    steps:
      - name: Prepare
        id: prepare
        run: |
          if [[ ${{ matrix.tag }} == latest ]]; then
            echo ::set-output name=file::Dockerfile
          else
            echo ::set-output name=file::Dockerfile.${{ matrix.tag }}
          fi

      - name: Docker login
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com

      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - name: Build the Docker image
        run: |
          docker buildx build \
            --cache-from "type=registry,ref=${CACHE_IMAGE}:${{ matrix.tag }}" \
            --cache-to "type=inline,mode=max" \
            --output "type=registry" \
            --tag ${CACHE_IMAGE}:${{ matrix.tag }} \
            --file ./${{ steps.prepare.outputs.file }} .

      # - name: Image history
      #   run: docker history ${CACHE_IMAGE}:${{ matrix.tag }}

      - name: Image size
        run: docker image ls
        #| grep ${CACHE_IMAGE}:${{ matrix.tag }}
